DDLL - > Capacitors.States write issue fixed.
The variant needs to be var, instead of out since we need to write in the Capacitor Variant interface.

When it is out, we get the following error:
OSError: [WinError 250477278] Windows Error 0xeedfade

py-dss-interface unit tests passed. 

git-svn-id: https://svn.code.sf.net/p/electricdss/code/trunk@3563 d8739450-1e93-4ef4-a0af-c327d92816ff